on:
 push:
   tags:
     - "v*"

# on: create

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update version
        run: |
          version=`git tag --sort=committerdate | tail -1 | sed 's/v//g'`
          sed -i.bak 's/__version__/$version/g' manifest.json

      - name: build release
        run: |
          mkdir -p ./release 
          zip -r ./release/extension.zip ./*;

      - name: upload & publish
        run: |
          ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&refresh_token=${{ secrets.REFRESH_TOKEN }}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ./release/extension.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ secrets.APP_ID }}"
          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${{ secrets.APP_ID }}/publish"
