on:
 push:
   tags:
     - "v*"

# on: create

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release GitHub Actions

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build release
        run: mkdir -p ./release && zip -r ./release/extension.zip ./*;

      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: './release/extension.zip'
          app-id: 'afhlbocnlpkgcdannmmlmagbhknnmcep'
          publish: true
